In [2]:
%matplotlib widget      
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
import pandas as pd
import sys
import os
from scipy import interpolate
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.io import fits
from tkinter import _flatten
from astropy.stats import poisson_conf_interval

In [5]:
path='/Users/baotong/Desktop/CDFS/'
os.chdir(path)

In [6]:
epoch_file=np.loadtxt('CDFS_epoch.txt')

In [7]:
print(epoch_file)

[[5.63211658e+07 5.63966590e+07 5.81000000e+02 7.54931700e+04]
 [5.97114425e+07 5.98090748e+07 1.43100000e+03 9.76322800e+04]
 [7.57771593e+07 7.58350502e+07 4.41000000e+02 5.78908400e+04]
 [7.63867966e+07 7.65206684e+07 5.82000000e+02 1.33871760e+05]
 [9.28787824e+07 9.29099257e+07 2.40600000e+03 3.11433100e+04]
 [9.29099257e+07 9.29712684e+07 2.40500000e+03 6.13427300e+04]
 [9.30655448e+07 9.31925208e+07 2.31200000e+03 1.26975930e+05]
 [9.33307243e+07 9.34283382e+07 1.67200000e+03 9.76139200e+04]
 [9.35855711e+07 9.36567206e+07 2.40900000e+03 7.11495100e+04]
 [9.37519500e+07 9.38854940e+07 2.31300000e+03 1.33543950e+05]
 [9.39798956e+07 9.41140019e+07 2.23900000e+03 1.34106360e+05]
 [3.06653427e+08 3.06701242e+08 8.59100000e+03 4.78152100e+04]
 [3.06880750e+08 3.06929582e+08 9.59300000e+03 4.88324600e+04]
 [3.07807271e+08 3.07859573e+08 9.71800000e+03 5.23022300e+04]
 [3.08023794e+08 3.08076158e+08 8.59300000e+03 5.23635600e+04]
 [3.08992387e+08 3.09054420e+08 8.59700000e+03 6.203258